site_name: Conia Boiler
copyright: © 2022 ebene fünf GmbH
theme:
    name: conia
repo_url: https://github.com/coniadev/boiler
extra:
    project: Boiler
plugins:
    - search
    - macros:
        module_name: docs/main
